"""
Job Alert Bot Configuration
"""
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Telegram Bot Config
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID_HERE")

# Location filter — Manado only
LOCATION_FILTER = "manado"

# Schedule Config (WITA timezone) — 24/7, cek setiap jam
TIMEZONE = "Asia/Makassar"
SCHEDULE_HOURS = list(range(0, 24))  # 24 jam

# Job Search Keywords — fokus Excel & Office (Manado)
SEARCH_KEYWORDS = [
    "Excel",
    "Microsoft Excel",
    "Data Entry",
    "Data Analyst",
    "Administration",
    "Admin",
    "Office",
    "Finance",
    "Accounting",
    "Accountant",
    "Bookkeeping",
    "Inventory",
    "Warehouse",
    "Logistics",
    "Operations",
    "Supply Chain",
    "Purchasing",
    "Procurement",
    "Marketing",
    "Customer Service",
    "Receptionist",
    "Secretary",
    "Manager",
    "Supervisor",
    "Staff",
    "Karyawan",
    "Manado",
]

# Exclude keywords — skip jobs containing these (sales-related)
EXCLUDE_KEYWORDS = [
    "sales",
    "salesman",
    "saleswoman",
    "sales executive",
    "sales representative",
    "sales officer",
    "sales staff",
    "sales agent",
    "sales associate",
    "sales consultant",
    "sales supervisor",
    "sales manager",
    "sales lead",
    "sales engineer",
    "sales coordinator",
    "sales support",
    "sales admin",
    "sales assistant",
    "sales intern",
    "sales trainee",
    "sales marketing",
    "business development",
    "bd officer",
    "bd executive",
    "bd manager",
    "account executive",
    "account officer",
    "key account",
    "customer success",
    "customer support",
    "call center",
    "telemarketing",
    "telesales",
    "marketing executive",
    "marketing officer",
    "marketing staff",
    "marketing coordinator",
    "digital marketing",
    "social media",
    "content creator",
    "influencer",
    "driver",
    "ojek",
    "ojol",
    "delivery",
    "courier",
    "rider",
    "pengantar",
    "waiter",
    "waitress",
    "kasir",
    "cashier",
    "koki",
    "cook",
    "chef",
    "barista",
    "bartender",
    "security",
    "satpam",
    "guard",
    "cleaning service",
    "cleaner",
    "office boy",
    "office girl",
    "supir",
    "helper",
    "asisten rumah tangga",
    "babysitter",
    "penjaga",
    "tukang",
    "buruh",
    "labor",
    "manual",
    "pabrik",
    "produksi",
    "production",
    "operator mesin",
    "machine operator",
    "teknisi",
    "technician",
    "mechanic",
    "montir",
    "electrician",
    "tukang listrik",
    "plumbing",
    "carpenter",
    "tukang kayu",
    "painter",
    "tukang cat",
    "welder",
    "tukang las",
    "kurir",
    "ekspedisi",
    "gudang",
    "forklift",
    "assistent",
    "frontliner",
    "resepsionis",
    "sekretaris",
    "akuntan",
    "pembukuan",
    "pajak",
    "auditor",
    "anggaran",
    "gaji",
    "rekrutmen",
    "pelatihan",
    "pengacara",
    "konsultan",
    "penasihat",
    "konselor",
    "psikolog",
    "psikiater",
    "terapis",
    "pekerja sosial",
    "lembaga swadaya masyarakat",
    "yayasan",
    "asosiasi",
    "serikat",
    "federasi",
    "konfederasi",
    "aliansi",
    "koalisi",
    "kemitraan",
    "kolaborasi",
    "konsorsium",
    "sindikat",
    "kartel",
    "monopoli",
    "oligopoli",
    "konglomerat",
    "multinasional",
    "transnasional",
    "internasional",
    "nasional",
    "provinsi",
    "kotamadya",
    "kecamatan",
    "kelurahan",
    "lingkungan",
    "masyarakat",
    "publik",
    "pemerintah",
    "negara",
    "federal",
    "teknologi informasi",
    "teknologi",
    "perangkat lunak",
    "perangkat keras",
    "pengembang",
    "peneliti",
    "analis",
    "operator",
    "administrator",
    "jaringan",
    "server",
    "basis data",
    "komputasi awan",
    "keamanan",
    "keselamatan",
    "kesehatan",
    "medis",
    "dokter",
    "perawat",
    "apoteker",
    "apotek",
    "rumah sakit",
    "klinik",
    "puskesmas",
    "posyandu",
    "sekolah",
    "universitas",
    "kampus",
    "akademi",
    "institut",
    "pendidikan",
    "guru",
    "dosen",
    "profesor",
    "pelatih",
    "pendamping",
    "psikiater",
    "terapis",
    "pekerja sosial",
    "lembaga swadaya masyarakat",
    "yayasan",
    "organisasi",
    "komunitas",
    "klub",
    "asosiasi",
    "serikat",
    "federasi",
    "konfederasi",
    "aliansi",
    "koalisi",
    "kemitraan",
    "kolaborasi",
    "konsorsium",
    "sindikat",
    "kartel",
    "monopoli",
    "oligopoli",
    "konglomerat",
    "multinasional",
    "transnasional",
    "internasional",
    "nasional",
    "provinsi",
    "kotamadya",
    "kecamatan",
    "kelurahan",
    "lingkungan",
    "masyarakat",
    "publik",
    "pemerintah",
    "negara",
    "federal",
]

# Job Sites to scrape
JOB_SITES = {
    "jobstreet": "https://www.jobstreet.co.id/en/job-search/{keyword}/",
    "kalibrr": "https://www.kalibrr.com/home/te/job-posting?q={keyword}",
    "indeed": "https://id.indeed.com/cari?q={keyword}&l=Indonesia",
    "linkedin": "https://www.linkedin.com/jobs/search/?keywords={keyword}&location=Manado",
    "topkarir": "https://www.topkarir.com/search?q={keyword}",
    "karir": "https://www.karir.com/search?q={keyword}",
    "loker": "https://www.loker.id/search?q={keyword}",
    "qerja": "https://www.qerja.com/search?q={keyword}",
    "glassdoor": "https://www.glassdoor.co.id/Job/manado-{keyword}-jobs-SRCH_IL.0,8_IC2981099_KO9,30.htm",
    "jobid": "https://www.job.id/search?q={keyword}",
    "street": "https://www.street.co.id/search?q={keyword}",
}

# Database
DB_PATH = os.path.join(os.path.dirname(__file__), "jobs.db")

# Notification settings
MAX_JOBS_PER_NOTIFICATION = 5
NOTIFICATION_INTERVAL_MINUTES = 60  # Check every hour 24/7
